### ISSUE TITLE
MD5 implementation unsupported

### ISSUE THREAD

**Issue by charavana** [klarna/HiveRunner#86] opened 2018-05-15 02:41 UTC
Hi Team we have religiously implemented the unit test with hive runners jar 3.2.1 snapshot
We are stuck with MD5 implementation  can U help?
Below is my code:
Step one:
    @HiveSQL(files = { my_source_table_ddl.hql,my_target_table_ddl.hql
}
 , autoStart = false)

    private HiveShell shell;

i am using below syntax to read the data from src to target  table in my junit:
shell.execute(Paths.get("HQL_Files/TABLES/mytable_INSERT.hql"));
my insert query has the MD5 in it concatination of 3 coulmns.
output:
when i run junit it says md5 function is not available in hive part of hive runner.
 observation:
i check couple of article it says hive.version 1.3.0 can resolve, but i see the hive runner pom with lower version 

Kindly can you help

**Comment by massdosage** [comment] 2018-05-31 18:07
Could you please send us the full stack trace and error message you are getting from Junit as well as your insert query? Feel free to change table names if you don't want to share anything sensitive but ideally we need to be able to reproduce this issue by using a setup as close to yours as possible.

**Comment by massdosage** [comment] 2018-07-18 21:47
Closing since no feedback received on how to reproduce.

**Closed by massdosage** 2018-07-18 21:47 UTC
