### ISSUE TITLE
HiveServerException

### ISSUE THREAD

**Issue by bhagatgopilal** [klarna/HiveRunner#44] opened 2016-07-18 07:36 UTC
This might be a existing issue: I see this error often and i believe its related to hadoop process being being interrupted. Is there a workaround for this. Help is much appreciated.

Caused by: HiveServerException(message:Query returned non-zero code: 1, cause: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:java.lang.RuntimeException: Error while running command to get file permissions : java.io.IOException: java.lang.InterruptedException

**Comment by PelleUllberg** [comment] 2016-08-23 07:09
Could you please provide a test case/setup to reproduce this error?

best regards
/Pelle

**Comment by massdosage** [comment] 2018-05-31 18:28
Closing since no feedback received for well over a year.

**Closed by massdosage** 2018-05-31 18:28 UTC
