### ISSUE TITLE
Running tests on OSX Sierra is very very slow

### ISSUE THREAD

**Issue by tao-findly** [klarna/HiveRunner#61] opened 2017-02-04 08:41 UTC
Currently I just upgrade my MacBook from El Capitan to Sierra. Suddenly my HiveRunner tests are running very very slow. Usually 5 tests only took 40 seconds, now need 8 mins. And I keep getting this error message in the console output:

`com.klarna.hiverunner.ThrowOnTimeout    - Test ran for 30 seconds. Timeout disabled. See class com.klarna.hiverunner.config.HiveRunnerConfig for configuration options.
`

Anyone has the same issue and how to solve it?

Thanks

**Comment by PelleUllberg** [comment] 2017-02-04 19:13
Hi, 

HiveRunner has an opt-in feature to timeout and rerun tests that deadlocks. This has historically happened when running tez. The printout you see is just an indication that some test cases are taking more than 30s. 

I recently upgraded to Sierra and have not noticed the same problems. I had some issues with UnknownHostException but nothing else. The full HiveRunner test suite clocks in at 3m 40s.

Some follow up questions:
- Are your tests still validating to true? 
- Can you pull the HiveRunner code base and run that test suite to verify that the problem is with HiveRunner and not with your project?
- Do the test cases run at normal speed on other environments?

best regards
/Pelle

**Comment by tao-findly** [comment] 2017-02-06 08:22
Hi Pelle,

Thanks for your quick reply.

Here is my answers for your questions:

- Yes, my tests still passed although it's very slow
- When I run 'mvn test' on HiveRunner code base, it just so slow and it took 30 mins and still running
- My test cases only took 20 seconds when I run them on Lubuntu 16.04

I also put 'log4j.logger.com.klarna.hiverunner.HiveServerContainer=DEBUG' into log4j.properties and try to find out where cause the issue. Here is some interesting log. You can see:

- Between 21:12:25 and 21:12:30, there has 5 seconds gap
- Between 21:12:43 and 21:12:53, there another 10 seconds gap

I don't know what cause these delays.

```
Running MainTest
DEBUG   06 Feb 2017 21:12:25 [MainTest#testSelectFromProfile]    org.apache.hadoop.util.NativeCodeLoader    - Trying to load the custom-built native-hadoop library...
DEBUG   06 Feb 2017 21:12:25 [MainTest#testSelectFromProfile]    org.apache.hadoop.util.NativeCodeLoader    - Failed to load native-hadoop with error: java.lang.UnsatisfiedLinkError: no hadoop in java.library.path
DEBUG   06 Feb 2017 21:12:25 [MainTest#testSelectFromProfile]    org.apache.hadoop.util.NativeCodeLoader    - java.library.path=/Users/taol/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
WARN    06 Feb 2017 21:12:25 [MainTest#testSelectFromProfile]    org.apache.hadoop.util.NativeCodeLoader    - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
DEBUG   06 Feb 2017 21:12:30 [MainTest#testSelectFromProfile]    org.apache.hadoop.hive.metastore.ObjectStore    - Overriding datanucleus.storeManagerType value null from  jpox.properties with rdbms
DEBUG   06 Feb 2017 21:12:30 [MainTest#testSelectFromProfile]    org.apache.hadoop.hive.metastore.ObjectStore    - Overriding datanucleus.autoStartMechanismMode value null from  jpox.properties with checked
.........
DEBUG   06 Feb 2017 21:12:43 [MainTest#testSelectFromProfile]    org.apache.hadoop.hive.metastore.ObjectStore    - Commit transaction: count = 0, isactive true at:
	org.apache.hadoop.hive.metastore.ObjectStore$GetHelper.commit(ObjectStore.java:2445)
DEBUG   06 Feb 2017 21:12:43 [MainTest#testSelectFromProfile]    org.apache.hadoop.hive.metastore.ObjectStore    - 1 entries retrieved using SQL in 34.908638ms
Warning: Shuffle Join MERGEJOIN[30][tables = [sbd, sq_1_notin_nullcheck]] in Stage 'Reducer 2' is a cross product
Query ID = taol_20170206211242_0b1e8b81-2874-43a9-944e-fa9862d7654b
Total jobs = 1
Launching Job 1 out of 1
WARN    06 Feb 2017 21:12:53 [MainTest#testSelectFromProfile]    com.klarna.hiverunner.ThrowOnTimeout    - Test ran for 30 seconds. Timeout disabled. See class com.klarna.hiverunner.config.HiveRunnerConfig for configuration options.
```

**Comment by tanni3009** [comment] 2017-07-10 15:06
Hi there!

I had the same issue, it seemed to be a problem of the OS and not HiveRunner. 
For me this solution: https://thoeni.io/post/macos-sierra-java/ worked!

**Comment by massdosage** [comment] 2018-05-31 18:20
Closing based on the last comment.

**Closed by massdosage** 2018-05-31 18:20 UTC
