### ISSUE TITLE
ERROR with CTE names

### ISSUE THREAD

**Issue by PedramBashiri** [klarna/HiveRunner#47] opened 2016-08-11 22:39 UTC
I'm using hiverunner 3.0.0.
The following query fails if there's an uppercase letter in cteName in the select \* clause, regardless of whether or not there's an uppercase in cteName in WITH clause.
To illustrate,

CASE 1:

```
hiveShell.executeQuery(
      """
        |WITH cteName as
        |  (SELECT someColumn
        |   FROM someTable
        |   WHERE someCondition
        |  )
        |SELECT *
        |FROM cteName
      """.stripMargin)
```

It fails.

CASE 2:

```
hiveShell.executeQuery(
      """
        |WITH ctename as
        |  (SELECT someColumn
        |   FROM someTable
        |   WHERE someCondition
        |  )
        |SELECT *
        |FROM ctename
      """.stripMargin)
```

Succeeds.

CASE 3:

```
hiveShell.executeQuery(
      """
        |WITH cteName as
        |  (SELECT someColumn
        |   FROM someTable
        |   WHERE someCondition
        |  )
        |SELECT *
        |FROM ctename
      """.stripMargin)
```

Succeeds.

Using hive and beeline:
The query  succeeds in all cases.

Here's the stack trace:

> java.lang.AssertionError
>     at org.apache.hadoop.hive.ql.parse.QB.rewriteViewToSubq(QB.java:237)
>     at org.apache.hadoop.hive.ql.parse.QB.rewriteCTEToSubq(QB.java:242)
>     at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.addCTEAsSubQuery(SemanticAnalyzer.java:1008)
>     at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.getMetaData(SemanticAnalyzer.java:1492)
>     at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.getMetaData(SemanticAnalyzer.java:1449)
>     at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.genResolvedParseTree(SemanticAnalyzer.java:10205)
>     at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:10256)
>     at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:10141)
>     at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:222)
>     at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:432)
>     at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:305)
>     at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1119)
>     at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1112)
>     at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:99)
>     at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:170)
>     at org.apache.hive.service.cli.operation.Operation.run(Operation.java:268)
>     at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:410)
>     at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatement(HiveSessionImpl.java:391)
>     at org.apache.hive.service.cli.CLIService.executeStatement(CLIService.java:245)
>     at com.klarna.hiverunner.HiveServerContainer.executeStatement(HiveServerContainer.java:112)
>     at com.klarna.hiverunner.builder.HiveShellBase.executeStatementWithCommandShellEmulation(HiveShellBase.java:103)
>     at com.klarna.hiverunner.builder.HiveShellBase.executeStatement(HiveShellBase.java:99)
>     at com.klarna.hiverunner.builder.HiveShellBase.executeQuery(HiveShellBase.java:89)
>     at com.klarna.hiverunner.builder.HiveShellBase.executeQuery(HiveShellBase.java:82)

**Comment by PelleUllberg** [comment] 2016-08-23 07:00
Sorry for the late reply. I've been on vacation. Thanks for the report. I've marked it as a bug for now until we get the time to fix it.

regards
/Pelle

**Comment by jorgenfalk** [comment] 2016-08-23 14:29
We can reproduce the issue in HiveRunner. 

Looks like a bug in Hive 1.2 and I found a very similar case  https://issues.apache.org/jira/browse/HIVE-10698. Solved in Hive 1.3 and 2.0.

When you run the query on the Hive CLI/Beeline, what version of hive are you using?

**Comment by jorgenfalk** [comment] 2016-08-23 15:13
I tested your CTE queries in Hive CLI 0.14 and 1.2. They all work regardless of case (as you pointed out). Maybe the Hive CLI does some toLowerCase() before passing the query to the HQL Parser.

The SemanticAnalyzer (and QueryBlock) in Hive 1.2 tries to do lower case on most of the identifiers, but sadly missed to do so for all identifiers in the CTE query...

I'll try to see if the Hive CLI does some magic or sets some properties that we can mimic in HiveRunner, otherwise I fear you have to use lower case all over your CTE's until we upgrade to Hive 1.3/2.0

**Comment by PedramBashiri** [comment] 2016-08-23 18:43
I'm using Hive 1.1.0

**Comment by PedramBashiri** [comment] 2016-08-23 18:50
Yeah I agree, I believe Hive CLI does something like toLowerCase() to every query because all the table and column names are stored in lower case in Hive.
For now I do toLowerCase() for all my CTEs before running the query, and everything seems to be working fine.

**Comment by prasanis** [comment] 2017-06-12 21:03
We ran into this issue today (Hive 1.2.1/ latest hiverunner build). Is there a plan to squash this?

**Comment by massdosage** [comment] 2018-05-31 18:26
Could you please try HiveRunner 3.2.1 (which was released today) and let us know if this is still an issue?

**Comment by massdosage** [comment] 2018-07-18 21:59
Closing this since no feedback received on above comment. I hope that https://github.com/klarna/HiveRunner/issues/73 fixed this.

**Closed by massdosage** 2018-07-18 21:59 UTC
Labels: bug
