### ISSUE TITLE
Hive runner does not support unbound proceeding or unbound following Syntax  while hive does

### ISSUE THREAD

**Issue by charavana** [klarna/HiveRunner#89] opened 2018-06-01 02:22 UTC
it was hive version 1.2.1 prior your upgrade also ,my comment was wrong ....kindly upgrade the hive  version from 1.2.1 to 2.X.x

please check if you can read an .HQL file with simple unbound proceeding or unbound following hql  in it

**Comment by massdosage** [comment] 2018-06-01 14:46
Duplicate of #87

**Closed by massdosage** 2018-06-01 14:46 UTC
