### ISSUE TITLE
Facing Issue while setting up hiverunner in local

### ISSUE THREAD

**Issue by Sneha22s** [klarna/HiveRunner#137] opened 2020-12-29 15:01 UTC
java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive configuration: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour ideally including the configuration files you are using (feel free to rename any sensitive information like server and table names etc.) 
Even better would be the source code of your unit test or a pull request against the HiveRunner unit tests containing a test that demonstrates the issue.

**Expected behavior**

**Logs**
Please add the log output from HiveRunner when the error occurs, full stack traces are especially useful.

**Versions (please complete the following information):**
 - HiveRunner Version: 
 - Hive Versions: for whatever version of Hive you are using for your tests

**Additional context**

**Comment by massdosage** [comment] 2021-01-04 11:30
What versions of Hive and HiveRunner and other dependencies are you using? It would also be helpful if you could fill out the various sections of the issue template above otherwise it's very hard to help debug what could be causing the problem.

**Comment by massdosage** [comment] 2021-03-09 15:42
The above is usually caused by an issue with Java and Hive versions but without further information it's impossible to know so closing this issue.

**Closed by massdosage** 2021-03-09 15:42 UTC
